import { Bairro } from './bairro';

export const BAIRROS: Bairro[]=[

   
    {nome:"Aeroporto"},
    {nome:"Asa Branca"},
    {nome:"Aviário"},
    {nome:"Baraúnas"},
    {nome:"Chácara São Cosme"},
    {nome:"Calumbi"},
    {nome:"Campo do gado novo"},
    {nome:"Campo Limpo"},
    {nome:"Capuchinhos"},
    {nome:"Caseb"},
    {nome:"Centro"},
    {nome:"Chácara São Cosme"},
    {nome:"Campo do Gado Novo"},
    {nome:"Cidade Nova"},
    {nome:"CIS"},
    {nome:"Conceição"},
    {nome:"Cruzeiro"},
    {nome:"Feira IV"},
    {nome:"Feira V"},
    {nome:"Feira VI"},
    {nome:"Feira VII"},
    {nome:"Feira IX"},
    {nome:"Feira X"},
    {nome:"Gabriela"},
    {nome:"Jardim Acácia"},
    {nome:"Jardim Cruzeiro"},
    {nome:"Kalilândia"},
    {nome:"Lagoa Grande"},
    {nome:"Lagoa Salgada"},
    {nome:"Limoeiro"},
    {nome:"Mangabeira"},
    {nome:"Muchila"},
    {nome:"Nova Esperança"},
    {nome:"Novo Horizonte"},
    {nome:"Papagaio"},
    {nome:"Parque Getúlio Vargas"},
    {nome:"Parque Ipê"},
    {nome:"Pedra do Descanso"},
    {nome:"Ponto Central"},
    {nome:"Queimadinha"},
    {nome:"Rua Nova"},
    {nome:"Santa Mônica"},
    {nome:"Santo Antônio dos Prazeres"},
    {nome:"São João"},
    {nome:"Sobradinho"},
    {nome:"SIM"},
    {nome:"Tomba"},
    {nome:"Viveiros"}
];